"""init db

Revision ID: 8266ff65f402
Revises: 
Create Date: 2021-06-15 09:01:27.771713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8266ff65f402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('sender_type', sa.String(length=64), nullable=False),
    sa.Column('receiver_id', sa.String(length=64), nullable=False),
    sa.Column('receiver_type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'sender_id', 'sender_type', 'receiver_id', 'receiver_type')
    )
    op.create_table('message_history_element',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('sort_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_history_element')
    op.drop_table('message_history')
    # ### end Alembic commands ###
